#ifndef __SOUNDS_H__
#define __SOUNDS_H__

class Sounds
{
public:
	static constexpr char* RESOURCE_FILE_NAMES[] = { 
		"Arachnotron_active.wav",  //0
		"Arachnotron_death.wav",
		"Arachnotron_sight.wav",
		"Arachnotron_walk.wav",
		"Archvile_active.wav",
		"Archvile_attack.wav",
		"Archvile_death.wav",
		"Archvile_pain.wav",
		"Archvile_sight.wav",
		"BFG.wav",
		"block_drop.wav", // 10
		"block_pick.wav",
		"Cacodemon_death.wav",
		"Cacodemon_sight.wav",
		"chaingun.wav",
		"chainsaw.wav",
		"ChainsawGoblin_attack.wav",
		"ChainsawGoblin_death.wav",
		"ChainsawGoblin_pain.wav",
		"ChainsawGoblin_sight.wav",
		"chime.wav", // 20
		"claw.wav",
		"Cyberdemon_death.wav",
		"Cyberdemon_sight.wav",
		"demon_active.wav",
		"demon_pain.wav",
		"demon_small_active.wav",
		"Dialog_Help.wav",
		"door_close.wav",
		"door_close_slow.wav",
		"door_open.wav", // 30
		"door_open_slow.wav",
		"explosion.wav",
		"fireball.wav",
		"fireball_impact.wav",
		"footstep1.wav",
		"footstep2.wav",
		"gib.wav",
		"glass.wav",
		"hack_clear.wav",
		"hack_fail.wav", // 40
		"hack_failed.wav",
		"hack_submit.wav",
		"hack_success.wav",
		"hack_successful.wav",
		"HolyWaterPistol.wav",
		"HolyWaterPistol_refill.wav",
		"hoof.wav",
		"impClaw.wav",
		"Imp_active.wav",
		"Imp_death1.wav", // 50
		"Imp_death2.wav",
		"Imp_sight1.wav",
		"Imp_sight2.wav",
		"item_pickup.wav",
		"loot.wav",
		"LostSoul_attack.wav",
		"Maglev_arrive.wav",
		"Maglev_depart.wav",
		"malfunction.wav",
		"Mancubus_attack.wav", // 60
		"Mancubus_death.wav",
		"Mancubus_pain.wav",
		"Mancubus_sight.wav",
		"menu_open.wav",
		"menu_scroll.wav",
		"monster_pain.wav",
		"Music_Boss.wav",
		"Music_General.wav",
		"Music_Level_End.wav",
		"Music_LevelUp.wav", // 70
		"Music_Title.wav",
		"no_use.wav",
		"no_use2.wav",
		"Pinkinator_attack.wav",
		"Pinkinator_death.wav",
		"Pinkinator_pain.wav",
		"Pinkinator_sight.wav",
		"Pinkinator_spawn.wav",
		"Pinky_attack.wav",
		"Pinky_death.wav", // 80
		"Pinky_sight.wav",
		"Pinky_small_attack.wav",
		"Pinky_small_death.wav",
		"Pinky_small_pain.wav",
		"Pinky_small_sight.wav",
		"pistol.wav",
		"plasma.wav",
		"platform_start.wav",
		"platform_stop.wav",
		"player_death1.wav", // 90
		"player_death2.wav",
		"player_death3.wav",
		"player_pain1.wav",
		"player_pain2.wav",
		"Revenant_active.wav",
		"Revenant_attack.wav",
		"Revenant_death.wav",
		"Revenant_punch.wav",
		"Revenant_sight.wav",
		"Revenant_swing.wav", // 100
		"rocketLauncher.wav",
		"rocket_explode.wav",
		"secret.wav",
		"Sentinel_attack.wav",
		"Sentinel_death.wav",
		"Sentinel_pain.wav",
		"Sentinel_sight.wav",
		"SentryBot_activate.wav",
		"SentryBot_death.wav",
		"SentryBot_discard.wav", // 110
		"SentryBot_pain.wav",
		"SentryBot_return.wav",
		"slider.wav",
		"Soulcube.wav",
		"SpiderMastermind_death.wav",
		"SpiderMastermind_sight.wav",
		"supershotgun.wav",
		"supershotgun_close.wav",
		"supershotgun_load.wav",
		"supershotgun_open.wav", // 120
		"switch.wav",
		"switch_exit.wav",
		"teleport.wav",
		"use_item.wav",
		"vending_sale.wav",
		"vent.wav",
		"VIOS_attack1.wav",
		"VIOS_attack2.wav",
		"VIOS_death.wav",
		"VIOS_pain.wav", // 130
		"VIOS_sight.wav",
		"weapon_pickup.wav",
		"Weapon_Sniper_Scope.wav",
		"Weapon_Toilet_Pull.wav",
		"Weapon_Toilet_Smash.wav",
		"Weapon_Toilet_Throw.wav",
		"Weapon_Toilet_Throw2.wav",
		"zombie_active.wav",
		"zombie_death1.wav",
		"zombie_death2.wav", // 140
		"zombie_death3.wav",
		"zombie_sight1.wav",
		"zombie_sight2.wav",
		"zombie_sight3.wav"
	};
};

#endif


